

	// int b=6;
	// int c=1;
	// cout<<((b>a)||(b>c));
	// if(a%2==0){
	// 	cout<<"number is even";
	// }
	// else{
	// 	cout<<"number is odd";
	// }


	// while(condition){
	// 	iteration
	// }

	// while(i<=10){
	// 	cout<<"hello	" <<i <<endl;
	// 	i++;
	// }

	// for (init ; condition ; operation){}

		// for (int i=1;i<=10;i++){
		// 	cout<<"hello	" << i <<endl;
		// }
	// int t;
	// cin>>t;
	// // for(int test=1;test<=t;++test){
	// 	while(t--){
	// 	int n;
	// 	cin>>n;
	// 	for(int i = 1;i<=n;++i){
	// 		for (int j=1;j<=i;++j){
	// 		cout<<"*";
	// 		}
	// 	cout<<endl;
	// 	}
	// }


// int t;
// cin>>t;
// while(t--){
// 	int n,m;
// 	cin>>n>>m;
// 	cout<<n+m<<endl;
// }}

	// for(int i=1;i<=n;++i){
	// 	for (int j=1;j<=i;++j){
	// 		cout<<"*";
	// 	}
	//  cout<<endl;
	// }
// }
// }
// 

//   int 10^9
// 	 long int 10^12
//   long long int 10^18
