// Day 2 of C++
// Type Mopdfiers


#include<bits/stdc++.h>
using namespace std;
int main(){

	unsigned int a; //declaration 
	a = 14 ; //Initialisation
	cout<<"the size of short int is  "<<sizeof(a)<<endl;
		float b = 3.14;
		double d = 14.1215454;
		bool c;
		char e;
		cout<<"Size of float	"<<sizeof(b)<<endl;
		cout<<"Size of double	"<<sizeof(d)<<endl;
		cout<<"Size of bool	"<<sizeof(c)<<endl;
		cout<<"Size of char	"<<sizeof(e)<<endl;

}
